# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="frisk"

# Automatically quote globs in URL and remote references
__remote_commands=(scp rsync)
autoload -U url-quote-magic
zle -N self-insert url-quote-magic
zstyle -e :urlglobber url-other-schema '[[ $__remote_commands[(i)$words[1]] -le ${#__remote_commands} ]] && reply=("*") || reply=(http https ftp)'

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git osx colored-man colorize pip python brew extract zsh-syntax-highlighting vi-mode history-substring-search autojump sudo vscode zsh-iterm-touchbar)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...

# Combined left and right prompt configuration.
# local smiley="%(?,%{$fg[green]%`}☺%{$reset_color%},%{$fg[red]%}☹%{$reset_color%})"

# Make vim the default editor
export EDITOR="vim"

# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X"

# Highlight section titles in manual pages
export LESS_TERMCAP_md="$ORANGE"

# Something to look for when waiting for auto-completition
COMPLETION_WAITING_DOTS="true"

# PROMPT='
# %{$fg[green]%}%~%{$reset_color%}
# ${smiley}  %{$reset_color%}'

# Set iTerm2 prompt on Touch Bar
#IT2PROMPT='$(~/.iterm2/it2setkeylabel set status "$(test -d .git && (echo "Git::$(basename `git rev-parse --show-toplevel`):$(git rev-parse --abbrev-ref HEAD)") || (echo -n "Not a repo"))")'

#PROMPT=$IT2PROMPT$PROMPT

# zmv
autoload -U zmv


sniff()
{
    if [[ $1 == '' ]]; then
        local INTERF="en0"
    else
        local INTERF=$1
    fi
    sudo ngrep -d $INTERF -t '^(GET|POST) ' 'tcp and port 80'
}

# Enable autojump
[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

# Load aliases
if [ -f ~/.aliases ]; then
    . ~/.aliases
fi

# Load Mac aliases
if [ `uname -s` = 'Darwin' ]; then
    . ~/.aliases_mac
fi

# Key binds
bindkey "^[[A" history-substring-search-up
bindkey "^[[B" history-substring-search-down

# Kubernetes
if kubectl > /dev/null 2>&1; then
  source ~/.dotfiles/kubernetes
fi

# Load go PATH
source ~/.dotfiles/go

# Load additional PATH
source ~/.dotfiles/path
