# Debug zsh startup
#zmodload zsh/zprof

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="powerlevel10k/powerlevel10k"

# Automatically quote globs in URL and remote references
__remote_commands=(scp rsync)
autoload -U url-quote-magic
zle -N self-insert url-quote-magic
zstyle -e :urlglobber url-other-schema '[[ $__remote_commands[(i)$words[1]] -le ${#__remote_commands} ]] && reply=("*") || reply=(http https ftp)'

# Disable zsh globbing (using wildcards in commands)
unsetopt nomatch

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Syntax highlight should be loaded before history-substring-search
plugins=(git osx colorize python brew extract history-substring-search autojump sudo vscode zsh-iterm-touchbar docker tmux golang fast-syntax-highlighting history-substring-search zsh-autosuggestions systemd fzf dirhistory history common-aliases)

source $ZSH/oh-my-zsh.sh

# Enable zsh plugins
source $HOME/.oh-my-zsh/custom/plugins/autoupdate-oh-my-zsh-plugins/autoupdate.plugin.zsh
source $HOME/.oh-my-zsh/custom/plugins/zsh-you-should-use/you-should-use.plugin.zsh
source $HOME/.oh-my-zsh/custom/plugins/forgit/forgit.plugin.zsh
fpath=($HOME/.oh-my-zsh/custom/plugins/zsh-completions/ $HOME/.dotfiles/completions $fpath)

# zmv
autoload -U zmv

# Enable autojump
[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

# Key binds
autoload -U history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
# bindkey "^[[A" history-beginning-search-backward-end
# bindkey "^[[B" history-beginning-search-forward-end

bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
export HISTORY_SUBSTRING_SEARCH_FUZZY=true

# Load additional shell rc
source ~/.dotfiles/shellconfig/shellrc.sh

# Wasmer
export WASMER_DIR="/Users/cdepaula/.wasmer"
[ -s "$WASMER_DIR/wasmer.sh" ] && source "$WASMER_DIR/wasmer.sh"  # This loads wasmer

# Use gitstatusd riscv64 built locally.
# To build, run `zsh -c "$(curl -fsSL https://raw.githubusercontent.com/romkatv/gitstatus/master/build.zsh)"`
if [ $CPUTYPE == "riscv64" ]; then
    GITSTATUS_DAEMON=$HOME/.dotfiles/bin/gitstatusd-linux-riscv64
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh

# if command -v tmux>/dev/null; then
#   [[ ! $TERM =~ screen ]] && [ -z $TMUX ] && exec tmux
# fi

export ZSH_TMUX_AUTOSTART=true

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Debug zsh startup
#zprof
