# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="frisk"
ZSH_THEME="spaceship"

# Automatically quote globs in URL and remote references
__remote_commands=(scp rsync)
autoload -U url-quote-magic
zle -N self-insert url-quote-magic
zstyle -e :urlglobber url-other-schema '[[ $__remote_commands[(i)$words[1]] -le ${#__remote_commands} ]] && reply=("*") || reply=(http https ftp)'

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

#ENABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git osx colored-man colorize pip python brew extract zsh-syntax-highlighting zsh-autosuggestions history-substring-search autojump sudo vscode zsh-iterm-touchbar)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...

# Combined left and right prompt configuration.
# local smiley="%(?,%{$fg[green]%`}☺%{$reset_color%},%{$fg[red]%}☹%{$reset_color%})"

# Make vim the default editor
export EDITOR="vim"

# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X"

# Highlight section titles in manual pages
export LESS_TERMCAP_md="$ORANGE"

# PROMPT='
# %{$fg[green]%}%~%{$reset_color%}
# ${smiley}  %{$reset_color%}'

# Set iTerm2 prompt on Touch Bar
#IT2PROMPT='$(~/.iterm2/it2setkeylabel set status "$(test -d .git && (echo "Git::$(basename `git rev-parse --show-toplevel`):$(git rev-parse --abbrev-ref HEAD)") || (echo -n "Not a repo"))")'

#PROMPT=$IT2PROMPT$PROMPT

# zmv
autoload -U zmv


sniff()
{
    if [[ $1 == '' ]]; then
        local INTERF="en0"
    else
        local INTERF=$1
    fi
    sudo ngrep -d $INTERF -t '^(GET|POST) ' 'tcp and port 80'
}

# Disable Spaceship prompt sections
SPACESHIP_PROMPT_ORDER=(
  time          # Time stamps section
  user          # Username section
  dir           # Current directory section
  host          # Hostname section
  git           # Git section (git_branch + git_status)
#  hg            # Mercurial section (hg_branch  + hg_status)
  package       # Package version
  node          # Node.js section
#  ruby          # Ruby section
  elixir        # Elixir section
  xcode         # Xcode section
#  swift         # Swift section
  golang        # Go section
#  php           # PHP section
  rust          # Rust section
#  haskell       # Haskell Stack section
#  julia         # Julia section
  docker        # Docker section
  aws           # Amazon Web Services section
  venv          # virtualenv section
  conda         # conda virtualenv section
  pyenv         # Pyenv section
#  dotnet        # .NET section
#  ember         # Ember.js section
  kubecontext   # Kubectl context section
#  exec_time     # Execution time
  line_sep      # Line break
  battery       # Battery level and status
#  vi_mode       # Vi-mode indicator
  jobs          # Background jobs indicator
  exit_code     # Exit code section
  char          # Prompt character
)

# Enable autojump
[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

# Load aliases
if [ -f ~/.aliases ]; then
    . ~/.aliases
fi

# Load Mac aliases and integrations
if [ `uname -s` = 'Darwin' ]; then
    source ~/.aliases_mac
    source ~/.iterm2_shell_integration.zsh
fi

# Key binds
bindkey "^[[A" history-substring-search-up
bindkey "^[[B" history-substring-search-down

# Load go PATH
source ~/.dotfiles/go

# Load additional PATH
source ~/.dotfiles/path

# Kubernetes
if [ -x "$(command -v kubectl)" ] > /dev/null 2>&1; then
  source ~/.dotfiles/kubernetes
fi

# Load hub (https://github.com/github/hub)
if [ -x "$(command -v hub)" ]; then
  eval "$(hub alias -s)"
fi
