zsh_themes:
  - https://github.com/romkatv/powerlevel10k

zsh_plugins:
  - https://github.com/carlosedp/zsh-iterm-touchbar
  - https://github.com/TamCore/autoupdate-oh-my-zsh-plugins
  - https://github.com/zsh-users/zsh-autosuggestions
  - https://github.com/zdharma-continuum/fast-syntax-highlighting
  - https://github.com/zsh-users/zsh-completions
  - https://github.com/zsh-users/zsh-history-substring-search
  - https://github.com/MichaelAquilina/zsh-you-should-use
  - https://github.com/Aloxaf/fzf-tab
  - https://github.com/wfxr/forgit
  - https://github.com/zpm-zsh/clipboard
  - https://github.com/ptavares/zsh-exa
  - https://github.com/carlosedp/mill-zsh-completions

go_apps:
  - "github.com/github/hub/v2@master"
  - "rsc.io/2fa@latest"
  - "golang.org/x/tools/cmd/benchcmp@latest"
  - "github.com/traefik/yaegi/cmd/yaegi@latest"
  - "github.com/rakyll/hey@latest"
  - "github.com/junegunn/fzf@latest"
  - "github.com/brancz/gojsontoyaml@master"
  - "mvdan.cc/sh/v3/cmd/shfmt@latest"
  - "github.com/hhatto/gocloc/cmd/gocloc@latest"
  - "github.com/charmbracelet/glow@latest"

rust_apps:
  - eza
  - bat
  - git-delta
  - hyperfine
  - ripgrep
  - fd-find

python_apps:
  - ansible-lint

coursier_apps:
  - cs
  - giter8
  - bloop-jvm
  - sbt
  - scala
  - scalac
  - scalafmt
  - scalafix
  - scala-cli
  - bleep

kubectl_plugins:
  - "ctx"
  - "ns"
  - "restart"
  - "access-matrix"
  - "stern"

base_packages:
  - sudo
  - openssh-server
  - curl
  - wget
  - tar
  - gzip
  - git
  - file
  - dbus
  - bc
  - bash-completion
  - hdparm
  - sysstat
  - less
  - vim
  - iptables
  - ipset
  - pciutils
  - iperf3
  - net-tools
  - jq
  - haveged
  - htop
  - zsh
  - tmux
  - neofetch
  - lshw
  - iotop
  - rsync
  - tree
  - autojump
  - smartmontools

debian_packages:
  - locales
  - ack-grep
  - nfs-common
  - apt-utils
  - openssh-client
  - build-essential
  - lm-sensors
  - ripgrep
  - python3-pip

fedora_packages:
  - ack
  - nfs-utils
  - "@Development tools"
  - openssh-clients
  - lm_sensors
  - python3-pip

alpine_packages:
  - ack
  - nfs-utils
  - build-base
  - openssh-client
  - py3-pip

extra_packages:
  - autojump
  - telnet
