- name: Workstation Setup
  hosts: localhost
  connection: local

  tasks:
    - name: Include Detect OS task
      ansible.builtin.include_tasks: detect_os.yml

    - name: Check if Developer Tools are installed (MacOS)
      ansible.builtin.command: xcode-select -p
      register: xcode_output
      changed_when: xcode_output.rc != 0
      when: is_macos

    - name: Install Developer Tools (MacOS)
      ansible.builtin.command: xcode-select --install
      when: xcode_output.rc != 0 and is_macos
      register: xcode_output_install
      changed_when: xcode_output_install.rc == 0

- name: Setup Shell
  ansible.builtin.import_playbook: setup_shell.yml

- name: Setup Shell Links
  ansible.builtin.import_playbook: setup_links.yml

- name: Setup Apps and Development Tools
  ansible.builtin.import_playbook: setup_apps.yml
