- name: Workstation Setup
  hosts: localhost
  connection: local

  tasks:
    - name: Include Detect OS task
      ansible.builtin.include_tasks: detect_os.yml

    - name: Install Developer Tools (MacOS)
      ansible.builtin.command: xcode-select --install
      when: is_macos
      register: xcode_output_install
      changed_when: xcode_output_install.stdout.find("command line tools are already installed") != -1

- name: Setup Shell
  ansible.builtin.import_playbook: setup_shell.yml

- name: Setup Shell Links
  ansible.builtin.import_playbook: setup_links.yml

- name: Setup Apps and Development Tools
  ansible.builtin.import_playbook: setup_apps.yml
