- name: Workstation Setup
  hosts: localhost
  connection: local

  tasks:
    - name: Set a variable if the OS is Linux or MacOS
      ansible.builtin.set_fact:
        is_linux: "{{ ansible_os_family == 'Debian' or ansible_os_family == 'RedHat' or ansible_os_family == 'Alpine' }}"
        is_macos: "{{ ansible_os_family == 'Darwin' }}"

    - name: Check if Developer Tools are installed (MacOS)
      ansible.builtin.command: xcode-select -p
      register: xcode_output
      changed_when: xcode_output.rc != 0
      when: is_macos

    - name: Install Developer Tools (MacOS)
      ansible.builtin.command: xcode-select --install
      when: xcode_output.rc != 0 and is_macos
      register: xcode_output_install
      changed_when: xcode_output_install.rc == 0

- name: Setup Zsh Shell
  ansible.builtin.import_playbook: setup_shell.yml

- name: Setup Shell Links
  ansible.builtin.import_playbook: setup_links.yml

- name: Setup Apps and Development Tools
  ansible.builtin.import_playbook: setup_apps.yml
